### ISSUE TITLE
Research paraphrasing models

### ISSUE THREAD

**Issue by ArtemKech** [AI-News-Team/AI-News#77]
Try to play with different models and see if there is a better one that we can use for our website.

**Comment by gpseal** [comment]
Have found another option with good potential:
https://huggingface.co/google/flan-t5-base

Has a huge number of downloads and is associated with Google.

This seems to be able to rewrite whole articles rather than sentences so could be ideal for our purposes.

**Comment by gpseal** [comment]
I have tested flan-t5 in its simplest form on entire articles using the following params:

outputs = model.generate(input_ids, 
                         min_length=wordCount+100,
                         max_length=wordCount*2,
                         length_penalty=2,
                         num_beams=4,
                         no_repeat_ngram_size=3)

This is a bare bones approach to using the model and I have struck the following errors:

BBC specific bodies of text are appearing at the bottom of certain articles, but are in no way associated with the content of the original scraped article:

![image](https://github.com/AI-News-Team/AI-News/assets/83617997/e1075d65-819f-48c9-b07a-475d2037a5b0)

When running the model on large articles the following warning is displayed: "Token indices sequence length is longer than the specified maximum sequence length for this model (1125 > 512). Running this sequence through the model will result in indexing errors"

Some articles are in different languages:
![image](https://github.com/AI-News-Team/AI-News/assets/83617997/53272c07-d928-488c-a35a-58f3218b7ef6)

**Comment by gpseal** [comment]
I am trying different settings for the T5 transformers, will document results here using the following article:

Original article:
"The Barbie film has hit the billion-dollar mark just 17 days after it was released, according to distributor Warner Bros.",
"The movie will finish the weekend with $1.03bn (£808m) in ticket sales at the global box office, it said ",
"It means Greta Gerwig has become the first woman to reach the milestone as a solo director.",
"Warner Bros described it as a \"watershed moment\".",
"Jeff Goldstein, president of domestic distribution in the US, said: \"No-one but Greta Gerwig could have brought this cross-generational icon and her world to life in such a funny, emotional and entertaining story... literally turning the entire world pink.\"",
"He said that long lines in cinemas and repeat viewings \"prove that movies are back\" after the cinema industry suffered due to pandemic lockdowns and competition from streamers.",
"Michael De Luca and Pam Abdy, co-chairs and bosses of Warner Bros Motion Picture Group, described audiences as \"embracing the Barbie movie in a profound way\".",
"The pink-hued film has received praise from critics and inspired scores of selfies at doll boxes installed in cinemas across the UK too.",
"Starring Margot Robbie as Barbie and Ryan Gosling as Ken, it has drawn in $459m so far in the US and $572m internationally.",
"Critics give their verdicts on the Barbie movie",
"Achieving \"Barbillion\" - as described by Warner Bros - is no mean feat. Just five other films have done so since the pandemic, including The Super Mario Brothers Movie earlier this year, Spider-Man: No Way Home, Top Gun: Maverick, Jurassic World Dominion and the Avatar sequel.",
"Cinema-goers have often paired a viewing of Barbie, which tells a coming-of-age story of the iconic doll, with Christopher Nolan's Oppenheimer - a story about the development of the first atomic bomb.",
"UK-based cinema chain Vue recently said both films had led to the ",
"Margot Robbie also served as one of the producers on Barbie. According to ",
"\"I think I told them that it'd make a billion dollars, which maybe I was overselling, but we had a movie to make, okay?!\" she told the publication.",
"The film's marketing campaign has been huge, with pink billboards installed in cities around the world while a pink Tardis also appeared at Tower Bridge.",
"Toy-maker Mattel is hoping to repeat the same success with other films.",
"Other Mattel brands - including Barney, Hot Wheels and Polly Pocket - are set to feature in upcoming Hollywood movies.",
"It released a soundtrack album and entered into more than 165 consumer product partnerships for the Barbie film, "

**Comment by gpseal** [comment]
![image](https://github.com/AI-News-Team/AI-News/assets/83617997/f079f29f-a904-4c66-a234-a5a9af013ef5)

'<pad> The pink-hued Barbie movie has raked in $1',
"03bn (£808m) in ticket sales at the global box office, according to the film's director Greta Gerwig, who is the first woman to reach the milestone as a solo director in a film since a pandemic in the 1980s - a year after the first atomic bomb was discovered in the United States - and a decade after it was released in the U",
'S',
' The film, which stars Margot Robbie as Barbie and Ryan Gosling as Ken, has drawn in $459m (£72m) so far in the US and $572m internationally, with a worldwide audience of more than 1',
'3bn viewers at the box office so far this year - making it the world\'s second-most-watched film in the history of film-making - according to a report by Warner Bros Motion Picture Group (WBPG) and the Hollywood Reporter (HBO) - which describes its success as "literally turning the entire world pink" and "turning the whole world pink"',
' (Click to watch a video of the film here - or if you haven\'t seen it yet - click here for a full list of all the films that have made it to the "Barbie Millions" box office - including The Super Mario Bros Movie, Spider-Man: No Way Home, Top Gun: Maverick, Jurassic World Dominion and the Avatar sequel - as well as The Super Nintendo Brothers Movie - to name just a few - it\'s worth a look to see if there\'s anything else you\'d like to know about the film - in the comments section of this week\'s New Year\'s Eve edition of the BBC\'s "Baby Talks" - featuring a live-action version of the iconic doll, which is due to be released on DVD in the UK on Friday',
') CLICK HERE to Try 2 RISK FREE issues of Entertainment Weekly',
' <unk> 2011 Entertainment Weekly and Time Inc',
' All rights reserved',
' This material may not be published, broadcast, rewritten or redistributed',
' If you have any questions or comments about this material, please contact our entertainment team on 0800 11 90 90 or visit our website at www', 'thebbc', 'co', 'uk', ' All material not expressly intended for use in any way other than as entertainment material and should be read in accordance with the terms and conditions of the Digital Millennium Copyright Activision and/or the Copyright Infringement Clause, which may contain material that is not intended for re-publication or republication in any form, including but not limited to, but is intended to protect the copyright holder\'s intellectual property (the "DMI") and other intellectual property relating to the protection of copyrighted works, or any other use which may be in retaliation for any alleged infringing, obscene, defamatory or indecent material, or to discuss any concerns you have with respect to any material which is not in accord with the Terms and Conditions of Use, or your objection to any of the statements or opinions expressed in this material', '</s>'

**Comment by gpseal** [comment]
![image](https://github.com/AI-News-Team/AI-News/assets/83617997/ffd9642d-7e58-45cb-ab1b-9880b38aaf13)


'<pad> The Pink Panther sequel has topped the box office with $1', '03bn (£8', '3bn) in ticket sales, its director Greta Gerwig has said', 
'<unk> br>Spoilers! The Pink Power Rangers Movie has been a smash success, with fans embracing the iconic doll and its world', 
"<unk> /br > It's not a surprise that the Pink Panther film has been in the making for a while",
 '<unk> br>Achieving the "Barbillion" mark is no mean feat, the director has said, and that the film is a "watershed moment"',
 "<unk> b<unk> r>Asked if she had been overselling, the actress's spokesman said: 'No-one but Gretta", '', '',
 ' could have brought this cross-generational icon and her world to life in such a funny, emotional and entertaining story', '', '', 
' literally turning the entire world pink', "'<unk> b><unk> bn>The film has drawn in $459m (£808m) in the US and $572m internationally, according to Warner Bros",
 '<unk> r<unk> /r>', '<unk> p>The pink-hued movie has drawn a lot of praise, with critics describing the film as a success', "<unk> brady-girl-girl's world is turning pink", '<unk> <unk> br<unk> /l> The film has drew in $458m (€29', '3m) so far in the UK and $573m internationally', '<unk> span<unk> /p><unk> r <unk> bd<unk> /hd<unk> /> <unk> p <unk> r / hd /r r<unk> p r ><unk> h <unk> rr n rr<unk> pg n', '', '', " <unk> spr p<unk> rt <unk> a n<unk> prt' <unk>!<unk> /span n' r pa<unk> t na <unk> l 
ne<unk>", '', '', " s ni<unk> m ny <unk> u nn<unk>? <unk> c nfl <unk> k <unk> e <unk> h nvt?<unk> /a! <unk> /c <unk> n <unk> o <unk>? ''</s>"

**Comment by gpseal** [comment]
![image](https://github.com/AI-News-Team/AI-News/assets/83617997/e890808a-1844-4b64-a00b-a4b0523942ce)

"<pad> The world's first pink-hued Barbie movie has raked in $1", '03bn (£808m) in ticket sales at the global box office, according to the film\'s director Greta Gerwig, who is the first woman to reach the milestone as a solo director in a single year, the Hollywood Reporter has learned, adding that it is a "watershed moment" for the film industry in the US and the US, as well as for Mattel brands like Barney, Hot Wheels and Polly Pocket, which are set to feature in upcoming Hollywood movies, despite the pandemic of a cholera outbreak in the UK and the United States in the past decade and a series of ill-fated atomic bombs inflicted on the world by a virus known as the "Barbie virus" - a disease that has ravaged the entertainment industry in recent years and led to the deaths of more than a quarter of the population of the UK in the first half of the 21st century - by the end of the 20th century, the New York Times has learned',
 ' The film has drawn in $459m (£72m) so far, and grossed $572m internationally, bringing the total worldwide box office total to $1', '05bn - more than double the previous record set by The Super Mario Bros Movie and Spider-Man: No Way Home earlier this year - and bringing in $1', '2bn in domestic ticket sales in the same time frame, the Times has said, citing the success of the film as the inspiration for its marketing campaign, which has been hailed as an "emotional and entertaining story" by critics and critics alike', " 'Barbie' is the pinnacle of filmmaking,' said a rep for Warner Bros Motion Picture Group, which owns the rights to the iconic doll, which is based on the novel of the same name by Margot Robbie and Ryan Gosling, who wrote the screenplay and directed the film, 'Baby's World' and 'Oppenheimer' - both of which are due to be released later this year, a statement from the company's chief 
executive, Jeff Goldstein, told the BBC's Sunday Evening Standard", '</s>']

**Comment by gpseal** [comment]
### Pegasus Model

![image](https://github.com/AI-News-Team/AI-News/assets/83617997/91014f18-bf7a-4ab9-867e-7356508fbd2d)

'Warner Bros.', 'The Avengers: Age of Ultron will finish the weekend with $1.03bn (£808m) in ticket sales at the global box office, it said.',
'Greta Gerwig is the first woman to reach the milestone as a solo director.', 
'"It\'s a moment I\'ve never seen before," he said. "It\'s a moment I\'ve never seen before. It\'s a moment I\'ve never seen before. It\'s a moment I\'ve never seen before', 
"Greta Gerwig's latest film, starring Jennifer Aniston, was released in the United States on March 18, 2014, and has grossed more than $70 million worldwide.", 
'The Chancellor of the Exchequer, David Cameron, has said cinemas are "back to normal" after a series of lockdowns in the wake of the pandemic.', 
'Michael De Luca and Pam Abdy, co-chairs and bosses of 
Warner Bros Motion Picture Group, described audiences as "embracing the Barbie movie in a profound way"', 
'Share this with Email Facebook Messenger Messenger Twitter Pinterest WhatsApp LinkedIn Copy this link These are external links and will open in a new window The film has been praised by critics for its pink-hued look.', 
"Disney's latest animated film, The Lion King, has drawn in $459m in the US and $572m internationally.", 'Critics give their verdict on the Barbie movie. Critics give their verdict on the Barbie movie. Critics give their verdict on the Barbie movie. Critics give their verdict on the Barbie movie. Critics give their verdict on the Barbie movie. Critics give their verdict on the Barbie movie', 'Top Gun: Mave, Spider-Man: No Way Home, Spider-Man: 
No Way Home, Spider-Man: No Way Home, Spider-Man: No Way Home, Spider-Man: No Way Home, Spider-Man: No Way Home, Spider-Man: No', "Nolan's 'Oppenheimer' - 
a story about the development of the first atomic bomb - has been praised by critics.",
'Vue decision to re-open its cinema in the UK. Vue said the two films had led to a re-opening of its cinema in the UK. Vue said the two films had led to a re-opening of its cinema', 'Margot Robbie\'s website, "Margot Robbie is a very talented actress.',
'"I think I told them that it\'d make a billion dollars, which maybe I was overselling, but we had a movie to make, okay?"',
"The film's marketing campaign has been huge, with billboards installed in cities around the world and a pink Tardis also appearing at Tower Bridge.", 'Mattel is hoping to repeat its success with other films.',
"Mattel is set to release a new line of toys in the US next year, according to a statement from the company's parent company.",
'The Walt Disney Company released a soundtrack album and entered into more than 165 consumer product partnerships for the Barbie film. It released a soundtrack album and entered into more than 165 consumer product partnerships for the Barbie film. The Walt Disney Company released a soundtrack album and entered into more than']}

**Comment by gpseal** [comment]
### Pegasus Model

![image](https://github.com/AI-News-Team/AI-News/assets/83617997/7cddce0a-4a7e-46b4-815d-e3d57295ea21)

'Warner Bros.', 'The Untouchables will finish the weekend with $1.03bn (£808m) in ticket sales, according to Deadline.', 'Gerwig said at the time: "This film isn\'t a career choice... but is an achievement and an honour.', '"Waiting to do everything right was also the most important moment 
in film history," said producer Sean Wesley, calling it a "watershed moment." "Wall Street is not a movie," Wesley said after watching a screening of the film, which was later', "Heidi Klum told the international 'Idyllic' magazine that the film has attracted  escalated critical and global acclaim.", 'BBC News correspondent Susan Bowles said filmgoers were "disappointed" at the declining cinema sector in the UK.', 'And when they tell "Baby" that she "can\'t make it without having some kind of fun" she says, a little \'who knows\' sentiment.', "'Juliet & Judy' has been given more attention by British film critics 
than anyone else, according to a release by distributor Zdj.", 'In a new series of films about a doll doll, Margot Robbie is revealed to be a sequel to the original.', "Critics compared Barbie's performance to her counterparts in Blade Runner and Star Wars: Battlefront: Legacy. Read them all at Movie Critic's Choice.", 'The MCU, and more.', "Nolan, while in it, portrays the Soviet Union's Cold War pre-eminence, and also offers a dramatic twist to the story.", 'U.S. in the making of the cult classic in the summer.', 'Barbie creator Mary Shelley, 62 percent of the production is from her.', '"We have a movie to make so we have to make it!"', "Kate Beckinsale tweeted a picture of herself in the early stages of the series, saying: 'She never gives up'!", 'Mattel hopes to prove that it can do the same for the movies that have made it on to the big screen', "Disney has had its first Disney TV show in nearly three years and 
the 'Halloween Mile' of Christmas comes to Disney's attention.", 'Barbie has also revealed that it has been involved in 220 mtv rentals globally.

**Comment by gpseal** [comment]
Pegasus ### Model

Adjusted input text
![image](https://github.com/AI-News-Team/AI-News/assets/83617997/97affea4-e4d3-461a-bb1a-1088c2ad0e10)


"the film's box office sales have been up 58.3 million dollars.", '"Epic Dreams" would be the fourth highest-grossing movie worldwide and the fourth highest at the box office, according to estimates from box office firm Box Office Research.', "Greta Gerwig's work at The State University of 
Washington", '"There\'s a great deal of emotion and energy in this world - it arouses the most powerful emotions.', 'Greta Gerwig was the leading actress in the 1990 film "Night of the Condors".', 'He said long lines and repeat viewings proving that movies are back were due to the triad lockdowns and the competition from streamers.', 'Michael De Luca and Pam Abdy, co-chairs and managers of Warner Bros Motion Picture Group, described audiences as "embracing the 
Barbie movie in a profound way".', 'london : box office smash london film box office smash has received good reviews from critics and its makers have also 
hailed it as a funny touch.', 'The film, starring Margot Robbie as Barbie, Ryan Gosling as Ken, has grossed $459m worldwide so far and $572m internationally.', 'reviews of the Barbie movie', 'Warner Bros movies have had its share of the "Barbillion" figure, however: Spider-Man: No Way Home, Top Gun, and Spider-Man: No Way Back have already achieved that feat.', 'a story about the development of the first atomic bomb', 'movie making scandal becoming "the only thing that was right," in the case of a two-year-old boy from India.', 'Margot Robbie was a producer on the show.', '"I think I told them that it\'d make a billion dollars, which maybe I was overselling, but we had a movie to make, okay?!" purchases', '"Patience" has garnered a lot of attention worldwide, although the film\'s marketing campaign has been more limited to a limited number of countries.', 'Mattel is hoping to repeat the success of other films.', 'Mattel is making a run for its money in the recent film industry, including some of its most famous characters.', 'The company released a soundtrack album and entered into more than 165 consumer product partnerships for the Barbie movie.']}
